name: builder-and-format-checker

on:  # When to run the ci-cd pipeline
    push: 
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs: 
    build:  # Job 1: build the code
        name: builder
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust Stable version
              uses: dtolnay/rust-toolchain@stable

            - name: Adding just
              run: apt install just
            
            - name: build the project
              run: just build
    
    fmt:  # Job 2: Check the formatting of the code 
        name: Format Checker
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust Stable version
              uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt
            
            - name: Adding just
              run: apt install just

            - name: format checking
              run: just fmt-check
